### ISSUE TITLE
Mejorar la impresión de los datos de la facturación.

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#10]
Mejorar la impresión de los datos resaltados en la imagen adjunta de la facturación.
![imagen](https://user-images.githubusercontent.com/43801800/46783514-8fb8aa80-ccf8-11e8-96db-8b544f277246.png)
[RND10-0021-16.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2467517/RND10-0021-16.pdf)

**Comment by ricardomendozaclaros** [comment]
Modificado con arreglos de QR
[Factura1810111558_3_1120.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2470552/Factura1810111558_3_1120.pdf)

**Comment by olimpiacf** [comment]
Por favor tomar en cuenta las siguientes modificaciones sugeridas por la contadora Ruth para la impresión de las facturas
Se adjunta imagen con modificaciones
![img-20181015-wa0000](https://user-images.githubusercontent.com/43801800/46994639-48a92b80-d0e3-11e8-8449-c13a4201a873.jpg)

Por favor tomar en cuenta la resolución de impuestos internos también
![img-20181015-wa0001](https://user-images.githubusercontent.com/43801800/46994722-a473b480-d0e3-11e8-99ef-f6a185e6c85b.jpg)

**Comment by ricardomendozaclaros** [comment]
se han hecho todas las modificaciones solicitadas

**Comment by olimpiacf** [comment]
Este error ya fue corregido, revisado en vlags y estable
