### ISSUE TITLE
Error en QR de Factura

### ISSUE THREAD

**Issue by rickyasg** [FrogTechDev/SolucionesAudioVisuales#11]
El reporte de Facturas no genera un código QR correcto para la lectura desde aplicaciones externas.
 
Lectura del Sitio: 236006028|509|385401700001719|**11102018**|60,00|60,00|7E-37-B0-FA-5C|6036268|0|0|0|0
Lectura de Factura Correcta. 1028627025|3645|263401800023207|**10/09/2018**|59.3|59.3|57-AE-42-4A-1C|0|0|0|0|0
El error puede ser generado por el formato de la fecha.
![whatsapp image 2018-10-11 at 11 19 42 am](https://user-images.githubusercontent.com/30187370/46815490-041b3a00-cd49-11e8-890b-d8e4a2e60384.jpeg)

**Comment by ricardomendozaclaros** [comment]
Corregido

            string quickResponseCode = string.Format("{0}|{1}|{2}|{3:dd/MM/yyyy}|{4}|{5}|{6}|{7}|0|0|0|0", e.NIT, f.NumeroFactura, f.NumeroAutorizacion, f.FechaRegistro, f.SubTotal, f.ImporteDebitoFiscal, f.CodigoControl, c.NIT);
