### ISSUE TITLE
Probar generador de codigo de control para el modulo de facturacion electronica

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#13]
Se adjunta archivo Zip para test de generación de código de control del sistema de facturación

[Release.zip](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2481626/Release.zip)

**Comment by olimpiacf** [comment]
Se realizaron los siguientes tests de verificacion de resultados:
1. verificar que los NumAutorizacion, NumFactura, NitCliente, FechaTransaccion, MontoTransaccion, LlaveDosificacion de la aplicacion generen un codigo de control verificado por la plataforma de impuestos nacionales.
2. verificar que el todos los 10 codigos de control sean validados y aceptados por la pltaforma de Impuestoa nacionales



[Certificado de generacion de codigo de control.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2487085/Certificado.de.generacion.de.codigo.de.control.pdf)
[validacion de codigo de control.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2487086/validacion.de.codigo.de.control.pdf)

**Comment by ricardomendozaclaros** [comment]
[Test.txt](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2570526/Test.txt)
5000 casos de prueba para facturacion
Codigo de Control

**Comment by ricardomendozaclaros** [comment]
queda pendiente el cierre departe tuya

**Comment by olimpiacf** [comment]
Aplicacion test de factura exitosa para 10 tests
