### ISSUE TITLE
Errores enmodulos de ventas facturacion

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#17]
Issues relacionados a los modulos de facturacion, ventas en documento word adjunto-
[Build date.docx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2614343/Build.date.docx)

**Comment by ricardomendozaclaros** [comment]
todos los  items de este documento fueron arreglados ya con otros bugs

**Comment by olimpiacf** [comment]
Este error ya fue corregido, revisado en lags y estable
