### ISSUE TITLE
Error en la emision de factura con monto decimales

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#18]
Cuando se registra montos con decimales en el pop up de datos de factura este hace el calculo redondeando los montos, las facturas son generadas con montos incorrectos.
por favor hacer la correcion con prioridad inmediata.
![imagen](https://user-images.githubusercontent.com/43801800/49200067-7a174700-f371-11e8-82cc-c5c2b1ed464c.png)

![imagen](https://user-images.githubusercontent.com/43801800/49200073-81d6eb80-f371-11e8-917d-f7bf1d5dbd30.png)

**Comment by ricardomendozaclaros** [comment]
![image](https://user-images.githubusercontent.com/22076613/49982516-59cfb680-ff33-11e8-8853-91fd88a7636e.png)

Please, ready for test

**Comment by olimpiacf** [comment]
This bug was fixed
