### ISSUE TITLE
Error en desplazamiento del focus en el form Venta de Productos

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#19]
El desplazamiento del focus en el form de Ventas, deveria iniciar al seleccionar el producto, el focus deberia ir hacia la cantidad marcandola con azul para su edicion por teclado, al pulsar la tecla TAB el focus deberia dirigirse hacia el precio del producto, marcandola con azul para su edicion.
![imagen](https://user-images.githubusercontent.com/43801800/49200380-e34b8a00-f372-11e8-8b42-59e668f1e0d6.png)

**Comment by olimpiacf** [comment]
el focus se desplaza en la direccion correcta, pero deberia tambien seleccionarse, por favor agregar la funcionalidad de marcar para seleccionar.
![imagen](https://user-images.githubusercontent.com/43801800/49268629-e90aa380-f436-11e8-934c-9c072611121d.png)

**Comment by ricardomendozaclaros** [comment]
se ha retirado los controles de agregar y disminuri del textbox y los facus tabulan deacuerdo al orden establecido

**Comment by olimpiacf** [comment]
Este error fue solucionado revisado en estable y en vlags
