### ISSUE TITLE
Errores en el formato del Reporte contable para exportacion

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#2]
Please take account that these should be the format for exporting and importing into client accountant system

[IMPOR.xlsx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2440462/IMPOR.xlsx)
![client email](https://user-images.githubusercontent.com/43801800/46388788-4931d300-c69c-11e8-94fa-6a9bfd081dcc.png)

**Comment by ricardomendozaclaros** [comment]
corregido

**Comment by olimpiacf** [comment]
El reporte no esta corregiso se adjunta imagen de las correcciones del cliente:

![imagen](https://user-images.githubusercontent.com/43801800/50744534-67a6ed80-11fa-11e9-831f-911ad65bbc21.png)

**Comment by olimpiacf** [comment]
Se modifico el reporte, se esperan modificaciones, verificado en vlags
