### ISSUE TITLE
Error cuando se genera codigo de control

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#20]
despues de la asignacion de.
![imagen](https://user-images.githubusercontent.com/43801800/49267749-494b1680-f432-11e8-8cc3-34eeaf913e8a.png)
se econtro error en la ejecucion del codigo de control, se adjunta imagen y texxto generado del error:
![imagen](https://user-images.githubusercontent.com/43801800/49267781-70094d00-f432-11e8-8ae1-ae630b77f2fe.png)

Could not find a part of the path 'c:\temp\log.txt'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost) at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost) at System.IO.StreamWriter..ctor(String path, Boolean append) at erpCodesur.TestFactura2.btnGetCodigosControl_Click(Object sender, EventArgs e) in C:\erpDemo\erpDemo\erpCodesur\TestFactura2.aspx.cs:line 49

**Comment by ricardomendozaclaros** [comment]
fue liberado test factura 2 y no presenta novedades

**Comment by olimpiacf** [comment]
Este error fue corregido
