### ISSUE TITLE
Se generan numeros de factura diferentes de la misma venta

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#21]
Se generan números de factura diferentes de la misma venta cuando se hace clic varias veces en el boton "Cobrar" de Datos para la factura popup, se adjuntan facturas descargadas.
![imagen](https://user-images.githubusercontent.com/43801800/49268174-5c5ee600-f434-11e8-81ff-de45aa88c289.png)
[Factura1811300000_0_51_0.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2631990/Factura1811300000_0_51_0.pdf)
[Factura1811300000_0_52_0.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2631991/Factura1811300000_0_52_0.pdf)
[Factura1811300000_0_53_0.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2631992/Factura1811300000_0_53_0.pdf)

**Comment by ricardomendozaclaros** [comment]
se ha corregido este punto bloqueando el boton "Cobrar"

**Comment by olimpiacf** [comment]
Este error ya fue solucionado revisado en estable y vlags
