### ISSUE TITLE
Pop up de series de productos se envian sin datos

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#22]
El formulario de series de productos se envía sin datos, estos fields deberían estar validados para no enviar productos sin serializar
![imagen](https://user-images.githubusercontent.com/43801800/49268361-751bcb80-f435-11e8-9f9a-4856e514f119.png)

**Comment by ricardomendozaclaros** [comment]
es un comportamiento esperado, no podemos esperar la  salida de  facturacion, para que valide como sujieres debemos iniciar el proceso de invetario y codificacion lo atrasaria a que alguien factura sin codificar

**Comment by olimpiacf** [comment]
El enhansemente fue implementado, revisado en vlags y estable
