### ISSUE TITLE
Error en modulo de reportes

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#23]
El modulo de reportes no esta mostrando los generadores de reportes mencionados en la lista de reportes:
-     Libro de Ventas
-     Arqueo de Caja
-     Ventas por
En la opcion de Libro de Ventas se muestra:
**Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.**
Requested URL: /Ventas/Reportes/LibroVentas.aspx
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3062.0 
![imagen](https://user-images.githubusercontent.com/43801800/49268774-db095280-f437-11e8-8788-7e8bd0ac0c49.png)
![imagen](https://user-images.githubusercontent.com/43801800/49268701-5d454700-f437-11e8-8c65-cb66a98c05e5.png)

**Comment by ricardomendozaclaros** [comment]
Fue arreglado con aterioridad

**Comment by olimpiacf** [comment]
Este erorr ya fue corregido, revisado en Vlags y estable
