### ISSUE TITLE
En dato para la factura descuento se muestra checked pero no se muestra el field de monto de descuento

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#24]
En dato para la factura descuento se muestra checked pero no se muestra el field de monto de descuento, el estado inicial al hacer un cobro deberia ser unchecked.
![imagen](https://user-images.githubusercontent.com/43801800/49286334-38b99100-f470-11e8-8236-561afccac31b.png)

**Comment by ricardomendozaclaros** [comment]
No se ha podido reproducir ese comportamiento

**Comment by olimpiacf** [comment]
se modifico la funcionalidad, revisado en vlags
