### ISSUE TITLE
Pop de prueba es mostrado en reporte de Libro de ventas

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#26]
![imagen](https://user-images.githubusercontent.com/43801800/49864774-a0110280-fdd9-11e8-8e59-cdfbb58cbf4b.png)

**Comment by ricardomendozaclaros** [comment]
se ha configurado este este facility para que este facility sea util desde distintos roles ej. 
Admin 
Usuario
 <Facility text="Libro Diario" ToolTip="Libro de Ventas" system="Reportes" facility="LibroVentas"  params="Rango=d" />
Rango=d  para que te muestre solo las transacciones del dia 
Rango=m para todas las transacciones del mes
sin parametros para que se personalize con dos fechas 

EmpresaId=0,1,2,...9 las transacciones de esa regional 

El Alert fue corregido

**Comment by ricardomendozaclaros** [comment]
asignado a Olimpia

**Comment by olimpiacf** [comment]
Este error ya fue corregido, revisado en vlags y estable
