### ISSUE TITLE
Coma de separacion de miles no se muestra en Venta de Productos ni en el libro diario

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#27]
Coma de separación de miles no se muestra en Venta de Productos ni en el reporte de  libro diario
![imagen](https://user-images.githubusercontent.com/43801800/49980905-d199e300-ff2b-11e8-9df3-72e0dc531d32.png)

![imagen](https://user-images.githubusercontent.com/43801800/49980910-d8285a80-ff2b-11e8-82f5-84e17fb84454.png)

**Comment by ricardomendozaclaros** [comment]
no es posbile en in input box, cambiaremos la prioridad

**Comment by olimpiacf** [comment]
Error en la columna P. Unitario, no muestra la coma de miles
![imagen](https://user-images.githubusercontent.com/43801800/50744886-4f849d80-11fd-11e9-8784-e5d8e9334aef.png)

**Comment by olimpiacf** [comment]
Se modificaro los cambios y se corrigio el reporte, revisado en vlags
