### ISSUE TITLE
Formato de exportacion no coincide se deberia desarrollar un nuevo modulo de exportacion

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#32]
El Formato de exportacion no coincide se deberia desarrollar un nuevo modulo de exportación para importar en el modulo del cliente.
 
![imagen](https://user-images.githubusercontent.com/43801800/50149885-c2e85e80-0292-11e9-8941-d7c241d37abd.png)

**Comment by olimpiacf** [comment]
se adjunta imagen copia de email. y archivo en formato excel.

![imagen](https://user-images.githubusercontent.com/43801800/50150115-6cc7eb00-0293-11e9-9586-40d07916136a.png)

[IMPOR(1).xlsx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2690171/IMPOR.1.xlsx)

**Comment by ricardomendozaclaros** [comment]
Arreglado con el bug #40

**Comment by olimpiacf** [comment]
Este error es duplicado sera corregido en adelante
