### ISSUE TITLE
Upgrate formato Libro de Ventas Standar  

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#36]
Agregar Columna de Descripción del producto de Libro Ventas

![imagen](https://user-images.githubusercontent.com/43801800/50342032-9da85a00-04f7-11e9-863d-ed9be840b3cb.png)

**Comment by ricardomendozaclaros** [comment]
El libro de ventas muestras las facturas emitidas y no asi los productos de esas facturas 
existen dos repsotes que ayudar a ver que se vendio en cada transaccion

**Comment by ricardomendozaclaros** [comment]
![image](https://user-images.githubusercontent.com/22076613/50466401-a2479500-0973-11e9-9ff4-32cf003a48cb.png)

El libro de ventas tiene un formato establecido por impuestos

**Comment by olimpiacf** [comment]
Formato de exportacion fue corregido, revisado en vlags y estable
