### ISSUE TITLE
No se muestra lista completa de sucursales en la edicion de XML

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#37]
No se muestra lista completa de sucursales en la edicion de XML, se deberia listar todas las sucursales de la empresa
![imagen](https://user-images.githubusercontent.com/43801800/50400522-a9955580-075d-11e9-87c6-3df36e323346.png)

**Comment by ricardomendozaclaros** [comment]
![image](https://user-images.githubusercontent.com/22076613/50451173-ccb03880-0908-11e9-9bd5-dc8b011883ec.png)
Implementando , se agrego un campo en la tabla empresas

**Comment by olimpiacf** [comment]
Error ya fue corregido, la funcionalidad esta disponible atravez de la parametrizacion de Empresas sucursales y dia y mes.
