### ISSUE TITLE
Urgente - Usuario regular de sucursal no guarda productos en el nomenclador

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#38]
Usuario regular de sucursal no guarda productos en el nomenclador

![imagen](https://user-images.githubusercontent.com/43801800/50400993-ed8a5980-0761-11e9-8780-6cc5bbed3e16.png)

**Comment by ricardomendozaclaros** [comment]
Arreglado modificando el tamaño del campo "Username" de la tabla ProductoPrecio, 
Nelson debe servisar si no existen inconsistencias de campos en toda la base de datos 
usuario (50 varchar)   -> username (10 varchar)

**Comment by olimpiacf** [comment]
este error fue corregido, revisado en vlags y estable con usuarios regulares
