### ISSUE TITLE
Errores en la impresion de la factura

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#39]
Correcciones criticas en la impresion de la Factura
![imagen](https://user-images.githubusercontent.com/43801800/50553547-2c973e00-0c7f-11e9-9cf6-dd1d64dc7562.png)

**Comment by ricardomendozaclaros** [comment]
![image](https://user-images.githubusercontent.com/22076613/50554133-71c16d00-0c8b-11e9-8bac-f2fecd1bcb8d.png)

Todas las observaciones fueron correginas 
Por favor Olimpia los campos  ,[Contribuyente] ,[GranActividad] deben ser actualizados coordinando con la contadora

**Comment by olimpiacf** [comment]
Este error fue corregido, revisado en vlags y estable
