### ISSUE TITLE
Agenda de Contactos 

### ISSUE THREAD

**Issue by ricardomendozaclaros** [FrogTechDev/SolucionesAudioVisuales#4]
Por favor Olimpia, construye una tabla de los contactos del proyecto con su telefono, correo y cargo

**Comment by olimpiacf** [comment]
Agenda Inicial, la tabla estara en el wiki para mañana, si tienen observaciones o comentarios por favor hacerlas en los comentarios.

![imagen](https://user-images.githubusercontent.com/43801800/46533221-d5492380-c871-11e8-97d9-37a8811953d9.png)
