### ISSUE TITLE
las columnas y resultados de reporte libro diario no matchean

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#40]
las columnas y resultados de reporte libro diario no matchean
![imagen](https://user-images.githubusercontent.com/43801800/50553630-feb2f900-0c80-11e9-91d9-a6d49cb3a420.png)

**Comment by ricardomendozaclaros** [comment]
![image](https://user-images.githubusercontent.com/22076613/50555291-73496000-0ca0-11e9-9b56-f8b64eef70d5.png)

Arreglado solo imprime el reporte de 16 Columnas ( Para el formato pdf no se requiere la especificacion 
 = 3 ) como en los otros formatos

**Comment by olimpiacf** [comment]
El reporte fue corregido, reviado en vlags y estable
