### ISSUE TITLE
Error en el Reporte Detalle COntable generado, Las facturas anuladas deben incluirse en el reporte

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#45]
Error en el Reporte Detalle Contable generado, columnas no coinciden con los formatos y datos solicitados por el cliente
se adjunta observaciones realizadas por el usuario
![imagen](https://user-images.githubusercontent.com/43801800/50744009-d2edc100-11f4-11e9-8a53-32b7c607c60d.png)

**Comment by olimpiacf** [comment]
Detalle de reporte de exportacion.

[EXPORTACION CORREGIDA 1.xlsx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2735218/EXPORTACION.CORREGIDA.1.xlsx)

**Comment by olimpiacf** [comment]
Facturas anuladas no se muestran en el reporte ni la descarga excel, todos los estados de las facturas deben ser mostrados en el reporte.
![imagen](https://user-images.githubusercontent.com/43801800/51295387-c2f09100-19ed-11e9-9ae0-54d69caf5018.png)

**Comment by ricardomendozaclaros** [comment]
![image](https://user-images.githubusercontent.com/22076613/51350027-7bb1e100-1a7d-11e9-8ee7-392b18b9b7a2.png)

repito, este trabajo ya fue realizado

**Comment by olimpiacf** [comment]
Las facturas anuladas deberian incluirse en el reporte.

**Comment by olimpiacf** [comment]
la funcionalidad no se implemento
