### ISSUE TITLE
Enhancement - Agregar descuento por producto en la facturacion

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#46]
1. Se deberia agregar la funcionalidad de descuento por producto en venta de productos
2. el descuento total (sumatorias) deberia mostrarse en el detalle de la factura.
3. Los descuentos por producto deberia imprimirse en la factura con el mismo monto generado en el pop up detalle de factura
4. Los descuentos por producto deberian mostrse tambien en los reportes de Arqueo Diario y Arqueo de productos.
5. en el reporte detalle contable deberia registrarse los decuentos por Item correspondiente de cada factura.

![imagen](https://user-images.githubusercontent.com/43801800/50748519-494bec80-1210-11e9-95e1-531ed1f0b48f.png)

**Comment by olimpiacf** [comment]
Se agrega foto con factura modelo para fields de descuentos

![img_20190107_230936](https://user-images.githubusercontent.com/43801800/50808837-d48fb580-12d6-11e9-8398-9a5afa4a1949.jpg)

**Comment by ricardomendozaclaros** [comment]
se ha implementado ya 
![image](https://user-images.githubusercontent.com/22076613/50810317-5aaffa00-12df-11e9-8719-be512cedc2b1.png)

please review for test

**Comment by olimpiacf** [comment]
este cambio fue implementado, revisado en vlags y estable
