### ISSUE TITLE
Error - Alert se abre en Recusrsos Humanos/Personal - DataTables warning: table id=grdPersonal - Requested unknown parameter 'DocumentoIdentidad' for row 0, column 4. For more information about this error, please see http://datatables.net/tn/4

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#47]
Error - Alert se abre en Recusrsos Humanos/Personal - DataTables warning: table id=grdPersonal - Requested unknown parameter 'DocumentoIdentidad' for row 0, column 4. For more information about this error, please see http://datatables.net/tn/4

![imagen](https://user-images.githubusercontent.com/43801800/51244352-4ca34e80-195b-11e9-9ea4-b93fdc6ef406.png)

**Comment by ricardomendozaclaros** [comment]
ya esta arreglado 
![image](https://user-images.githubusercontent.com/22076613/51274111-b0059e80-19a4-11e9-8707-ce509ceead90.png)

**Comment by olimpiacf** [comment]
el error ya no se muestra, revisado en vlags
