### ISSUE TITLE
Resultado de filtro no muestra las ventas por filtros, en Detalle Contable

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#48]
Resultado de filtro no muestra las ventas por filtros, en Detalle Contable

![imagen](https://user-images.githubusercontent.com/43801800/51245002-e91a2080-195c-11e9-9bd5-71ec36aba3d4.png)

**Comment by ricardomendozaclaros** [comment]
No se puede reproducir el error 

![image](https://user-images.githubusercontent.com/22076613/51272783-75e6cd80-19a1-11e9-884b-23b47cb96942.png)

**Comment by olimpiacf** [comment]
Se corrigio, verificado en vlags
