### ISSUE TITLE
Actualizar Listado de Personal base de datos de stable 

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#49]
Actualizar Listado de Personal por sucursal en la base de datos de stable, se adjunta listado actualizado en formato excel.
[Libro1.xlsx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2763903/Libro1.xlsx)

**Comment by ricardomendozaclaros** [comment]
ya fue actualizado
