### ISSUE TITLE
Modificaciones al modulo de Productos

### ISSUE THREAD

**Issue by ricardomendozaclaros** [FrogTechDev/SolucionesAudioVisuales#5]
Modificar Logo Productos
Agregar Campo "Precio de Costo"
Descripcion SingleLine
Modificar el  Reporte Carta: Agregar Descripcion,Precio de Venta y Compra
Modificacion de reporte Multisucursal

**Comment by ricardomendozaclaros** [comment]
arreglado, no existem multisucursal para un producto

**Comment by olimpiacf** [comment]
este error se cierra por error en la solicitud del cliente.
