### ISSUE TITLE
Publicacion Release Server 

### ISSUE THREAD

**Issue by ricardomendozaclaros** [FrogTechDev/SolucionesAudioVisuales#6]
Por favor publicar este release

[bkWidex20181003.zip](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2444754/bkWidex20181003.zip)
[Release.zip](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2444756/Release.zip)

**Comment by rickyasg** [comment]
el Release fue publicado en el servidor de pruebas SNOW con IP publica 200.87.69.148
en el puerto 8087. el aplicativo se encuentra publico, la informacion de acceso se encuentra en los WiKi
**No se puedo realizar la publicación en servidor del cliente, ya que cuenta con una instalación de el servidor de  FILEMAKER sobre IIS y no podemos realizar modificaciones. El IIS en sel servidor del cliente no se encuentra con todas las configuraciones necesarias para el aplicativo, asi q es necesario contar con un servidor nuevo, para realizar todas la configuraciones requeridas y no afectar a otros servicios que el cliente tiene en producción.**

**Comment by ricardomendozaclaros** [comment]
ya fue publicado en el servidor del cliente 
http://186.121.240.74/
