### ISSUE TITLE
Enhancements 

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#65]
1.Agregar Descripcion en el reporte de arqueo de productos
2. Quitar la sumatoria del excel export del reporte de detalle contable
3. quitar la restriccion del descuento en ventas facturacion
![image](https://user-images.githubusercontent.com/43801800/58390499-8833e080-7fff-11e9-8a60-2e248b7f3713.png)

**Comment by ricardomendozaclaros** [comment]
1 Se modifico el reporte y se mantuvo la sumatoria ya que esta bien 

![image](https://user-images.githubusercontent.com/22076613/58377474-814d9500-7f4f-11e9-861f-c58e22f0f34d.png)

2. Quitar la sumatoria del excel export del reporte de detalle contable
No se tiene la suma en este reporte 

3. quitar la restriccion del descuento en ventas facturacion
a sido comentado

![image](https://user-images.githubusercontent.com/22076613/58377533-1ac97680-7f51-11e9-91ee-d0a76843121c.png)

**Comment by olimpiacf** [comment]
3. enhancement 3 no se aplico
![image](https://user-images.githubusercontent.com/43801800/58390784-f927c800-8000-11e9-94b2-24ea91ebd8fc.png)

2. Quitar sumatoria del Reporte descarga Excel de Libro de ventas
![image](https://user-images.githubusercontent.com/43801800/58391136-7869cb80-8002-11e9-97ef-e9e6e74bc2c9.png)

**Comment by ricardomendozaclaros** [comment]
fixed, please test to changed

**Comment by olimpiacf** [comment]
Se realizaron los cambios y se agrego la descripcion
