### ISSUE TITLE
Error al abrir modulo de catalogo de productos

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#67]
Error al abrir modulo de catalogo de productos
el error se muestra cada que se abre o se busca un producto
![image](https://user-images.githubusercontent.com/43801800/58388872-6718c300-7ff2-11e9-915f-20a8535adbc3.png)

**Comment by ricardomendozaclaros** [comment]
se ha incluido en campo Codigo de Importacion

fixed revisar por favor

**Comment by olimpiacf** [comment]
los mensajes de error ya no se muestran, revisado en Vlags
