### ISSUE TITLE
Error Grave - Factura emitida con efectivo menor al precio facturado

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#70]
La factura es emitida con un Monto efectivo menor al precio facturado
El cambio se restante se muestra en negativo

![image](https://user-images.githubusercontent.com/43801800/58390235-32ab0400-7ffe-11e9-8794-8ad5974f45fe.png)
![image](https://user-images.githubusercontent.com/43801800/58390264-5cfcc180-7ffe-11e9-9d5a-fd15f112372f.png)

**Comment by ricardomendozaclaros** [comment]
fixed, test test the changes

**Comment by olimpiacf** [comment]
La factura se emite correctamente de acuerdo a las normativas de impuestos nacionales
