### ISSUE TITLE
Error - Detalle de ventas no se muestra datos de ventas de nueva sucursal

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#71]
en Ventas - Reportes - Detalle de ventas no se muestra datos de ventas de nueva sucursal
![image](https://user-images.githubusercontent.com/43801800/58391287-3b520900-8003-11e9-838c-fc741701412f.png)

**Comment by ricardomendozaclaros** [comment]
se modifico la vista [vwGetReporteVentas] y se parcho en estable esto corrige varias cosas porque no se tengia los precios



from facturas fac
	inner join PedidoProductos pp on pp.pedidoId = fac.pedidoId
	inner join erpProductos p on p.ProductoId = pp.ProductoId
	inner join erpPrecios pre on pre.ProductoId = p.ProductoId A**ND pre.TipoPrecio='VENTA' AND pre.IsActivo=1**
	inner join Pedidos ped on ped.PedidoId = pp.PedidoId
	inner join erpEmpresas emp on emp.EmpresaId = fac.EmpresaId

**Comment by olimpiacf** [comment]
el detalle de ventas se muestra en la nueva sucursal
