### ISSUE TITLE
Importacion de datos y revision del modelo 

### ISSUE THREAD

**Issue by ricardomendozaclaros** [FrogTechDev/SolucionesAudioVisuales#8]
Por favor 
Urgente una revision del modelo

necesitamos una parametrizacion de usuarios y sucursales segun las fotos adjuntas
segun el archivo  Word del organigrama
segun las fotos tomdas de las sucursales
segun todos los certificados de impuetos 

[ORGANIGRAMA NACIONAL WIDEX.docx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2462266/ORGANIGRAMA.NACIONAL.WIDEX.docx)
![f-santa cruz](https://user-images.githubusercontent.com/22076613/46699662-84765980-cbe8-11e8-9c16-c20787d5ce96.jpg)
![f-sucre](https://user-images.githubusercontent.com/22076613/46699663-84765980-cbe8-11e8-986a-d49e6a434068.jpg)
[F-Tarija.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2462281/F-Tarija.pdf)
![f-trinidad](https://user-images.githubusercontent.com/22076613/46699664-850ef000-cbe8-11e8-819d-03fd48e25df0.jpg)
[F-Cochabamba.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2462282/F-Cochabamba.pdf)
![f-el alto](https://user-images.githubusercontent.com/22076613/46699665-850ef000-cbe8-11e8-9664-3da59ecee623.jpg)
![f-la paz](https://user-images.githubusercontent.com/22076613/46699666-850ef000-cbe8-11e8-8b87-6fdbf996a9fa.jpg)
![f-oruro](https://user-images.githubusercontent.com/22076613/46699667-85a78680-cbe8-11e8-9a95-a75db94e5434.jpg)
![f-quillacollo](https://user-images.githubusercontent.com/22076613/46699668-85a78680-cbe8-11e8-8a19-253511105a4c.jpg)
![sucre 1](https://user-images.githubusercontent.com/22076613/46699675-89d3a400-cbe8-11e8-97fa-5822ffa26fe9.jpg)
![sucre 2](https://user-images.githubusercontent.com/22076613/46699676-8a6c3a80-cbe8-11e8-8d45-0d6e11f677a5.jpg)
![trinidad 1](https://user-images.githubusercontent.com/22076613/46699677-8a6c3a80-cbe8-11e8-9f67-5b116fcc819b.jpg)
![trinidad 2](https://user-images.githubusercontent.com/22076613/46699678-8a6c3a80-cbe8-11e8-8c32-3418135d597f.jpg)
![cochabamba 1](https://user-images.githubusercontent.com/22076613/46699679-8a6c3a80-cbe8-11e8-9a1b-4972d728c61a.jpg)
![cochabamba 2](https://user-images.githubusercontent.com/22076613/46699681-8a6c3a80-cbe8-11e8-9cb6-46e9e14740a0.jpg)
[dosificacion Suc TARIJA.pdf](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2462284/dosificacion.Suc.TARIJA.pdf)
![el alto 2](https://user-images.githubusercontent.com/22076613/46699682-8b04d100-cbe8-11e8-9d05-62a6f2b0300f.jpg)
![el alto1](https://user-images.githubusercontent.com/22076613/46699683-8b04d100-cbe8-11e8-85ec-52a08c691b31.jpg)
![la paz 1](https://user-images.githubusercontent.com/22076613/46699684-8b04d100-cbe8-11e8-8309-ed121a664378.jpg)
![la paz 2](https://user-images.githubusercontent.com/22076613/46699685-8b04d100-cbe8-11e8-989e-44dfa25f3355.jpg)
![oruro 1](https://user-images.githubusercontent.com/22076613/46699686-8b9d6780-cbe8-11e8-8f0c-23cc7ec082f6.jpg)
![oruro 2](https://user-images.githubusercontent.com/22076613/46699688-8b9d6780-cbe8-11e8-91d9-68d4f05589a7.jpg)
![quillacollo 1](https://user-images.githubusercontent.com/22076613/46699689-8b9d6780-cbe8-11e8-858a-adc004e8b35d.jpg)
![quillacollo 2](https://user-images.githubusercontent.com/22076613/46699690-8b9d6780-cbe8-11e8-825d-93a81febcdf9.jpg)
![santa cruz 1](https://user-images.githubusercontent.com/22076613/46699691-8b9d6780-cbe8-11e8-88cd-8f03383f605a.jpg)
![santa cruz 2](https://user-images.githubusercontent.com/22076613/46699692-8b9d6780-cbe8-11e8-957f-792d62dbe6ad.jpg)
[LISTADO.xlsx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2462285/LISTADO.xlsx)
[Datos Soluciones Auditivas.xlsx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2462286/Datos.Soluciones.Auditivas.xlsx)
[ORGANIGRAMA NACIONAL WIDEX.docx](https://github.com/FrogTechDev/SolucionesAudioVisuales/files/2462287/ORGANIGRAMA.NACIONAL.WIDEX.docx)

**Comment by ricardomendozaclaros** [comment]
![image](https://user-images.githubusercontent.com/22076613/49983207-9f8e7e00-ff37-11e8-8814-786c937d7911.png)


toda la data fue importada en la tabla Empredas

**Comment by olimpiacf** [comment]
La documentacion fue revisada los reportes correspondientes seran agregados a la funcionalidad
