### ISSUE TITLE
Boton "Cobrar" queda inactivo cuando se trata de crear una factura con descuento

### ISSUE THREAD

**Issue by olimpiacf** [FrogTechDev/SolucionesAudioVisuales#9]
Submit del boton "Cobrar" queda inactivo cuando se trata de crear una factura con descuento
Severidad: Alta
![imagen](https://user-images.githubusercontent.com/43801800/46782027-7ca2dc00-ccf2-11e8-8f99-0d81a53584d9.png)

**Comment by ricardomendozaclaros** [comment]
ya fue atendido

**Comment by olimpiacf** [comment]
Este error ya fue corregido, revisado con vlags y estable
